### ISSUE TITLE
zexall test suite failing

### ISSUE THREAD

**Issue by simonowen** [redcode/Z80#1]
Running the [zexall](http://mdfs.net/Software/Z80/Exerciser/Spectrum/) test suite with your Z80 core is showing some result mismatches.  The very first ADC/SBC hl,rr  test is failing, though since it's just a batched test it doesn't help identify what the problem is.  Some of the later tests also report issues, but it could be from the same root cause.

I've run the same zexall.tap test through some of the popular Spectrum emulators and they're passing, so I believe the tests to be valid.  I haven't had a chance to investigate it yet, but wanted to check you weren't already aware of it.

**Comment by redcode** [comment]
Thanks for the info. Some years ago I used ZEXALL to compare Kio's zxsp core with my own and I found that my implementation passed more tests so I didn't worry much about that. But now you've told me that, I think it's time to solve the remaining inaccuracies.

Maybe it's related to MEMPTR, an esoteric record that I haven't emulated yet, or maybe it's due to incorrect emulation of flags.

Whatever it is, I'll take a look at it as soon as possible.

Thank you.

**Comment by simonowen** [comment]
Here's a snapshot from Ant Attack that seems to show an issue, perhaps the same issue: https://home.simonowen.com/ant_attack.sna

A few seconds after it loads the ants should come in from the top-left of the screen.  As they circle in front of the wall they face different directions and they're sometimes displayed as a wall block instead of an ant. The girl to rescue is lying on the first wall inside the compound, but isn't visible. Rotating the player left using M and then walking forward a few steps with V also causes him to disappear.

I've tested the same snapshot in Spectaculator, SpecEmu and Spin, and they all run normally.  I don't know if they all claim to support MEMPTR, to know whether it's a factor here.  It's possible the game could have a bug in relation to its flag testing, like Sabre Wulf does for the rhino issue, but it would be good to identify it and support it.

Just in case, it may be worth you trying the same snapshot in MicroZX.  I've been testing the Z80 core under Windows, as built using Visual Studio 2017. If you don't see the issue in MicroZX (presumably running under macOS or Linux), it could be a casting/truncation issue.

**Comment by redcode** [comment]
Thanks, I'll try Ant Attack. I'm going to work on this tomorrow afternoon.

BTW, how have you tested the Z80 core? which ZX Spectrum emulator have you used? Did you used Z, or removed Z dependency and changed needed macros and types of Z?

I'm asking this because Z support for Visual C++ is outdated, I was planning to work con it next month. Currently only Clang is up to date and works OK.

As a note, I have to say that I made changes in the emu a few weeks ago, to make it more secure against hypothetical type promotion related bugs. Maybe that can be the reason of the incorrect emulation of the adc/sbc hl,rr instructions. Last time I tested the core these instructions passed the tests.

**Comment by redcode** [comment]
Ahhh, another thing:

If you find the bugs, please, feel free to create a pull request.

**Comment by simonowen** [comment]
Thanks for looking into this.  I'll run some execution traces against another Spectrum emulator to see if I can narrow down what might be happening.  You'll be first to know if I find anything :)

I'm using Z, but only to satisfy what the Z80 core needs.  The rest of the Spectrum setup is my own code, though there isn't really much to it beyond holding the interrupt line low for 32T every frame.  For I/O it's only handling the keyboard, with all other ports returning 0xff.  Display and sound are output only, so they can't affect the way the emulation runs.

I've looked at a few open source Z80 cores for this project, and yours was the easiest to try integrating first. The lack of memory contention support hasn't been a problem, and I may get away without it.  Speed is key as I need to run hundreds of cores in parallel -- that's been no problem on my trusty old i7 2600K.

If the Ant Attack snapshot shows the same problem for you, it's probably a core issue.  If it doesn't then it could be a quirk when it's used with Visual Studio.  I can let you know which pre-processor definitions I've defined for the core, to make sure they're correct.  I'm also building for x64 currently, so I'll go back to try x86 to see if it's different.

I've run 20+ other Spectrum games without issue, so I don't know why this one is special.

**Comment by redcode** [comment]
Hello Simon,

The bug has been addressed. I screwed up by changing the argument types of the functions that calculated the VF flag. Now it's fixed and the `adc/sbc hl,rr` instructions (and another ones) are working great again.

But, as before, some instructions are not 100 % accurate, so I'm going to fix them all. Only give me a few days.

**Comment by redcode** [comment]
https://github.com/redcode/Z80/commit/aaa744654bf3e93c842df1bee36ae8ba17318a10

**Comment by redcode** [comment]
Hello Simon,

The bug has been addressed. I screwed up by changing the argument types of the functions that calculated the VF flag. Now it's fixed (https://github.com/redcode/Z80/commit/aaa744654bf3e93c842df1bee36ae8ba17318a10) and the `adc/sbc hl,rr` instructions (and another ones) are working great again.

But, as before, some instructions are not 100 % accurate, so I'm going to fix them all. Just give me a few days.

**Comment by redcode** [comment]
I've compared the results of zexall of Kio's Z80 to mine. My emulator pass more tests. His emu doesn't have any OK that in my emu is an error, and most of the errors in common have the same wrong CRC (only 5 different CRCs).

I'm passing the tests to fuse, which is a pretty decent and accurate emulator, to compare.

**Comment by redcode** [comment]
I've compared the results of zexall of Kio's Z80 core to mine. My emulator pass more tests. His emu doesn't have any OK that in my emu is an error, and most of the errors in common have the same wrong CRC (only 5 different CRCs).

I'm passing the tests to Fuse, which is a pretty decent and accurate emulator, to compare.

Do you know if zexall pass all tests in the real hardware?

This guy (The JavaCPC author) pass all tests in his emu: http://www.cpcwiki.eu/forum/emulators/zexall-z80-tests/

This is his emulator's source code: https://sourceforge.net/p/javacpc/svn/HEAD/tree/JavaCPC/src/

**Comment by redcode** [comment]
I've compared the results of zexall of Kio's Z80 core to mine. My emulator pass more tests. His emu doesn't have any OK that in my emu is an error, and most of the errors in common have the same wrong CRC (only 5 different CRCs).

I'm passing the tests to Fuse, which is a pretty decent and accurate emulator, to compare.

**Comment by redcode** [comment]
These are the results of my Z80:

![z80](https://user-images.githubusercontent.com/355282/47068124-b0e33480-d1eb-11e8-9179-26227f39a780.png)

**Comment by simonowen** [comment]
Great! Thanks for spending the time to get this sorted so quickly.  I'll pull the latest version tonight and see how I get on.

I don't think passing zexall is considered a requirement by most people, especially if it's relying on MEMPTR in areas that only special tests with notice. I know Phil doesn't consider it worth the cycles to implement it all in Fuse, except for a few places where real software is known to need them.  Matching Fuse output is plenty good enough in my eyes.

The Fuse core was actually next on my list to try, and I may return to it should I need memory contention in the future.  For now yours is probably the fastest choice for me. :)

**Comment by redcode** [comment]
Results of Kio's [zxsp](http://k1.spdns.de/Develop/Projects/zxsp-osx/Distributions/):

![zxsp](https://user-images.githubusercontent.com/355282/47098692-faf00880-d233-11e8-8c24-450b1b37f8a0.png)

**Comment by redcode** [comment]
The last one: [Retro Virtual Machine](http://www.retrovirtualmachine.org/en/):
(This one claims to pass all tests... but pretty the same)

![retro virtual machine](https://user-images.githubusercontent.com/355282/47100418-b9615c80-d237-11e8-9ebd-9267fa75065d.png)

**Comment by simonowen** [comment]
The updated version fixes all my quirks, so I'm happy to close this issue -- thanks again!

Patrick Rak has written a newer Z80 test suite that it might be worth trusting over zexall: https://www.dropbox.com/s/33he0chzu6v7xym/z80test-1.0.zip

It has a few test variants:
- z80full - tests all flags and registers.
- z80doc - tests all registers, but only officially documented flags.
- z80flags - tests all flags, ignores registers.
- z80docflags - tests documented flags only, ignores registers.
- z80ccf - tests all flags after executing CCF after each instruction tested.
- z80memptr - tests all flags after executing BIT N,(HL) after each instruction tested.

I've run the z80doc tests with your updated core, and it shows some mismatches. I don't know of any real software affected by them yet.
