### ISSUE TITLE
How to link Z80 static in Makefile project?

### ISSUE THREAD

**Issue by omikron88** [redcode/Z80#10]
Hello,
How may I use Z80 in my Makefile project and link it statically to final executable, without need of Z80.so or Z80.dll?
I have Z80 as subdir of my project files and Zeta as another subdir.

**Comment by redcode** [comment]
If you are not using CMake, you will need to add `<Z80-subdir>/sources/Z80.c` to the list of source files in your Makefile, and both `<Zeta-subdir>/API` and `<Z80-subdir>/API` to the list of include directories.

Example:

```make
CC=gcc
INCLUDE_DIRS = -Iexternal/Zeta/API -Iexternal/Z80/API
OPTIONS = -DZ80_WITH_EXECUTE -DZ80_WITH_FULL_IM0 -DZ80_WITH_IM0_RETX_NOTIFICATIONS -DZ80_WITH_Q -DZ80_WITH_ZILOG_NMOS_LD_A_IR_BUG
SOURCE_FILES = example.c external/Z80/sources/Z80.c

all: example

example: $(SOURCE_FILES)
	$(CC) $(INCLUDE_DIRS) $(OPTIONS) $(SOURCE_FILES) -o example
```

The following zip contains a skeleton project with a Makefile and a small C program that uses the Z80 library. To try it, put both Zeta and Z80 into the `external` subdirectory.

[Example.zip](https://github.com/user-attachments/files/18184122/Example.zip)

**Comment by omikron88** [comment]
The problem is with MSYS2. Zeta says "Invalid Z_COMPILER key" . It is not able to identify the compiler probably.

**Comment by redcode** [comment]
I see.

I'll add support for MSYS2 to Zeta.

BTW, you can use the pre-build static library for Windows, and the header file [`Z80-no-deps.h`](https://github.com/redcode/Z80/releases/download/v0.2-pre-2024-09-21/Z80-no-deps.h), which does not need Zeta.

https://github.com/redcode/Z80/releases/tag/v0.2-pre-2024-09-21

**Comment by redcode** [comment]
Since this has nothing to do with Z80, but with Zeta, I will close this Issue. As I said, I will add support for MinGW-w64 to Zeta. If you wish to comment further on this issue, please open an issue or a discussion in the Zeta repository.
