### ISSUE TITLE
How to set BUSREQ or WAIT?

### ISSUE THREAD

**Issue by atirut-w** [redcode/Z80#8]

**Comment by redcode** [comment]
$\overline{\texttt{WAIT}}$ is not explicity set by using any function. Instead, you should directly add to `Z80::cycles` the desired wait T-states. Do it within the callback corresponding to the M-cycle in which the WAIT signal is generated.

As for $\overline{\texttt{BUSREQ}}$, there is a limitation, although I have not yet explained it adequately in the documentation: The Z80 CPU responds to the $\overline{\texttt{BUSREQ}}$ signal at the end of each M-cycle. That means that as long as the signal lasts, the cycle is frozen and the CPU does not go to the next cycle until the signal ends. If the signal is short, this can be emulated in the same way as $\overline{\texttt{WAIT}}$, that is, by adding to `Z80::cycles` the duration of the signal. However, if the signal is very long, for example in the case of a DMA operation that moves a large amount of memory or similar, then we have the problem that, even if we add the T-states:

1. if that amount makes the global T-state counter of your machine object exceed the total T-states of 1 emulated machine frame,
2. and the signal does not occur in the last M-cycle of the instruction,
3. and there are still others in which memory will be accessed,

problems may arise (depending on what is being emulated and whether a precise control of the T-state within the frame in which a memory access is performed is required, of course).

I think the best solution is to do directly as in $\overline{\texttt{WAIT}}$ (i.e., add the duration of the $\overline{\texttt{BUSREQ}}$ signal to `Z80::cycles`) and assume that the signal started just in the last M-cycle of the instruction.

The alternative would be to save the state of the `Z80` object and use `setjmp()` or similar in the callback where the signal occurs to avoid finishing executing the instruction. But I don't think it would be worth it, it would be quite complex to do.
